### ISSUE TITLE
NettyHttpClient的sendRequest方法只能调用一次吗

### ISSUE THREAD

**Issue by zohar-soul** [jpush/jpush-api-java-client#134]
第二次调用就会报错
```java
Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x0db43730]

java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:855)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:778)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:479)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126)
	at cn.jiguang.common.connection.NettyHttpClient.sendRequest(NettyHttpClient.java:82)


```

**Comment by helperhaps** [comment]
刚刚将 https://github.com/jpush/jpush-api-java-client/blob/master/example/main/java/cn/jpush/api/examples/PushExample.java#L97 这个 try 语句块复制了一份放在后面，运行测试是 ok 的

**Comment by zohar-soul** [comment]
@helperhaps https://github.com/jpush/jpush-api-java-client/blob/8d9537a49001c8eecea8c694dcbd40275586cb33/example/main/java/cn/jpush/api/examples/PushExample.java#L72
是sendRequest方法 那个异步的。
原因估计是sdk里面发送后直接断开netty连接了。

**Comment by helperhaps** [comment]
这个设计就是这样的，所以只有重新 new 了
